name:  Marp-CI
permissions:
    contents: write
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
concurrency:
    group: export
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

      - name: marp-action
        env: 
          MARP_ARGS: "--theme-set blue.css -I slides/ --output dist/" # this is the important line change since our marp command is different from the standard one
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PUBLISH_TO_BRANCH: master
          BASE_URL: https://ihuangz.github.io/Marp-courses/
